spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:bankdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  messages:
    basename: i18n/messages
    cache-duration: -1
    encoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2-console

