spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:bankdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

